name: # <- имя проекта (dbt init name)
  target: dev
  outputs:
    dev:
      type: clickhouse
      server: clickhouse 
      port: 8123
      user: default
      password: ""
      database: default
      schema: default