FROM apache/superset:latest

USER root

# Ставим pip в .venv
RUN /app/.venv/bin/python -m ensurepip \
    && /app/.venv/bin/python -m pip install --upgrade pip setuptools wheel

# Фиксируем версии совместимые с Superset
RUN /app/.venv/bin/python -m pip install \
        "SQLAlchemy<2" \
        clickhouse-sqlalchemy==0.2.2 \
        clickhouse-driver==0.2.9

USER superset
